### ISSUE TITLE
Issue with last navigation item

### ISSUE THREAD

**Issue by w3work** [CodyHouse/cd-floating-side-navigation-changelog#1]
Hi,

I found a bug that is not related to my own code. This error can be traced live in your component.
The following approach:
If you scroll from the beginning of the page to the end, the last menu item (marker) is not marked as active. If you click on it (section 4), it is marked as active. The error now is that I can no longer click on the upper menu items. Nothing is happen here.
I come back to the beginning of the page with scrolling, but I can't click in the menu bar.
When I get back to the top, the side menu also works again.

The issue gets visible, when the upper section is still visible at the end of the side. So in your example Section Three. If this sextion is still in the viewport of the side, then the last menu item is not getting active.

https://drive.google.com/file/d/1E0s9lrmA1kTAasAc5hkiWdTVNHNvoP5q/view

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We are working on this issue. We'll push a fix soon. Cheers!

**Comment by w3work** [comment]
Hi Claudia,
thanks for pushing this up.

I found another bug inside this component, thats why i invited you to the repository i'm working on. I uploaded it to Github here, to share with you. Here the link, hope you can see it: https://github.com/w3work/rumpelbraue.de

So back to the problem:
I want to create a one-page website and i use the floating-side navigation as a component here.
The navigation is inside the "responsive sidebar", witch i set as a static element. so onle the main content on the left side is scrollable.
The floating side navigation is working correct, when i click on each navigation element. here the site scrolls smooth from section to section.
The problem is, that is not working correct when i start from top and scroll to the bottom of the side. Then the "active" state of the navigation is not triggered correct. It random changes to first, second, third or fourth navigation item.

https://drive.google.com/file/d/1S6GF7vQQw_uIR3pzmSw3c-R9G0xV2_J-/view

**Comment by claudia-romano** [comment]
Hi there, I have opened a different issue for your problem:
https://github.com/CodyHouse/cd-floating-side-navigation-changelog/issues/2

If we could please use different issues for different problems, that would be great. It will help us keep track of different bugs (and other users to find the proper issue easily).

We have pushed a commit that should fix the bug of this issue ('Issue with click on last navigation item'). 

Please let me know if you are still experiencing it. If you don't, please close this issue. 

You can follow issue https://github.com/CodyHouse/cd-floating-side-navigation-changelog/issues/2 for additional updates.

**Comment by w3work** [comment]
Hi Claudio,
thanks for the update. Issue is fixed and it is working now.
