### ISSUE TITLE
Issue with nav indicator update on scroll

### ISSUE THREAD

**Issue by claudia-romano** [CodyHouse/cd-floating-side-navigation-changelog#2]
Selected nav indicator is not correctly updated on scrolling:
https://drive.google.com/file/d/1S6GF7vQQw_uIR3pzmSw3c-R9G0xV2_J-/view

**Comment by claudia-romano** [comment]
Hi @w3work, we just pushed an updated version of the component that should fix this issue. Let me know if you're still experiencing the same problem. Cheers!

**Comment by w3work** [comment]
Hi Claudia,

the problem is fixed and it is working very fine now! Thank you for your great great support here.
